### ISSUE TITLE
Nickname invalid

### ISSUE THREAD

**Issue by jonashelsen** [AskalotCQA/askalot#3]
I tried logging into askalot but it bumps me with the following error message:

validation failed: nickname invalid

for the record my nickname is Jonas-H, could it be that the askalot nickname parser does not allow for "-"?

Thanks!

**Comment by isrba** [comment]
Thank you very much for this bug report.

The problem was caused by different characters allowed in username in Askalot and in edX. edX allows  "letters, numbers, underscores (_), and hyphens (-)." Askalot originally allowed the same characters except hyphens. We have just add a hyphen to validation regexp and deployed the new version at edX.

**Comment by adrianhuna** [comment]
Closing this issue as the changes have been implemented.
